name: Izgradi .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Postavi .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Vrati ovisnosti
      run: dotnet restore
    
    - name: Izgradi
      run: dotnet build --no-restore
      
    - name: Testiraj
      run: dotnet test --no-build
